version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: chirp-db
    environment:
      POSTGRES_DB: chirp
      POSTGRES_USER: chirp
      POSTGRES_PASSWORD: chirp
    volumes:
      - chirp_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: chirp-redis
    ports:
      - "6379:6379"
    volumes:
      - chirp_redis_data:/data
    command: redis-server --appendonly yes

  backend:
    image: ghcr.io/andrewj2006/chirp/backend:latest
    container_name: chirp-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chirp
      SPRING_DATASOURCE_USERNAME: chirp
      SPRING_DATASOURCE_PASSWORD: chirp
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/andrewj2006/chirp/frontend:latest
    container_name: chirp-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  chirp_db_data:
  chirp_redis_data:
